#!/bin/sh
while getopts ":k:t:o:c:q:i:d:e:f:j:" opt
do
    case $opt in
        k)
	key=${OPTARG#*=}
        ;;
        t)
	type=${OPTARG#*=}
        ;;
        o)
	pass=${OPTARG#*=}
	;;
	c)
	control=${OPTARG#*=}
        ;;
	q)
	q=${OPTARG#*=}
        ;;
	i)
	ip=${OPTARG#*=}
        ;;
        d)
        btime=${OPTARG#*=}
        ;;
		e)
        etime=${OPTARG#*=}
        ;;
        f)
        file=${OPTARG#*=}
        ;;
	    j)
        task=${OPTARG#*=}
        ;;
        ?)
        echo "argv** is error!!"
        exit 1;;
    esac
done
if [ -n "$file" ]; then
     mv $file ./$q$key'.session'

fi
if [ -n "$etime" ]; then
     python3 ../POC/telegramcontrol.py -ip=$ip -ty=$control -phone=$q$key -st=$btime -task=$task -et=$etime
else
     python3 ../POC/telegramcontrol.py -ip=$ip -ty=$control -phone=$q$key -st=$btime -task=$task
fi
#echo "python3 ../POC/telegramcontrol.py $ip $control $q$key $btime"



